# Use zsh as default shell
set-option -g default-shell /bin/zsh

# Start zsh as a login shell (recommended)
# set-option -g default-command "/bin/zsh -c cd /home/hugo/code && /bin/zsh"
# Unbind the default prefix

unbind C-b

# Set new prefix to Ctrl+a
set-option -g prefix C-a

# Make sure you can still send literal Ctrl+a to programs
bind C-a send-prefix

# Split panes
bind | split-window -h
bind - split-window -v

# Switch panes using hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload config quickly
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
# Respawn pane in its current directory
bind R respawn-pane -k -c "#{pane_current_path}"
# Split horizontally and stay in same directory
bind | split-window -h -c "#{pane_current_path}"

# Split vertically and stay in same directory
bind '"' split-window -v -c "#{pane_current_path}"
# Kill pane immediately, no prompt
unbind x
bind x kill-pane

# plugins
set -g @plugin 'tmux-plugins/tpm'

# Status & themes
set -g @plugin '2kabhishek/tmux2k'
set -g @plugin 'aaronh/tmux-which-key'
# tmux2k must see these before TPM sources the plugin.
set -g @tmux2k-left-sep 
set -g @tmux2k-right-sep 
set -g @tmux2k-left-plugins 'session cwd'

set -g @tmux2k-right-plugins 'cpu ram battery'
# Window naming: use current directory
set -g automatic-rename on
set -g allow-rename off
set -g automatic-rename-format '#{b:pane_current_path}'

unbind &
bind q kill-window


# Toggle synchronized panes with prefix + y
# bind y setw synchronize-panes

# Correct terminal setup for Nerd Fonts
# set -g default-terminal "tmux-256color"
# set -ga terminal-overrides ",xterm-256color:Tc"
# bind -r y split-window -h -l 33% -c "#{pane_current_path}" "copilot"
bind -r y split-window -h -l 33% -c "#{pane_current_path}" 'SESSION="ai-$(pwd | md5sum | cut -c1-8)"; tmux has-session -t "$SESSION" 2>/dev/null || tmux new-session -d -s "$SESSION" -c "$PWD" "zsh -i -c silver-ai"; exec env TMUX="" tmux attach-session -t "$SESSION"'

setw -g mode-keys vi
set -sg escape-time 10
# Setup 'v' to begin selection, just like Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to yank (copy), just like Vim
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
set -g mouse on

set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
set -g base-index 1
# initialize TPM (keep this at bottom)
run '~/.tmux/plugins/tpm/tpm'
set -g allow-passthrough on
